#!/bin/python3

import math
import os
import random
import re
import sys

def matchingStrings(stringList, queries):
    # Create a dictionary to store the occurrences of each string in stringList
    occurrences = {}
    
    # Count occurrences of strings in stringList
    for string in stringList:
        occurrences[string] = occurrences.get(string, 0) + 1

    # Create a list to store the results
    result = []
    
    # Count occurrences of each query string in the dictionary
    for query in queries:
        result.append(occurrences.get(query, 0))

    return result

if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    stringList_count = int(input().strip())

    stringList = []

    for _ in range(stringList_count):
        stringList_item = input()
        stringList.append(stringList_item)

    queries_count = int(input().strip())

    queries = []

    for _ in range(queries_count):
        queries_item = input()
        queries.append(queries_item)

    res = matchingStrings(stringList, queries)

    fptr.write('\n'.join(map(str, res)))
    fptr.write('\n')

    fptr.close()
